version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: quickorder_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: quickorder
      POSTGRES_PASSWORD: quickorder123
      POSTGRES_DB: quickorder_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - red-datos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quickorder -d quickorder_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: rodito221/quickorder-backend:1.0
    build: ./backend
    container_name: quickorder_backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: quickorder
      DB_PASSWORD: quickorder123
      DB_NAME: quickorder_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - red-app
      - red-datos

  frontend:
    image: rodito221/quickorder-frontend:1.0
    build: ./frontend
    container_name: quickorder_frontend
    restart: unless-stopped
    networks:
      - red-acceso

  proxy:
    image: rodito221/quickorder-proxy:1.0
    build: ./proxy
    container_name: quickorder_proxy
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
    networks:
      - red-acceso
      - red-app

networks:
  red-acceso: { driver: bridge }
  red-app: { driver: bridge }
  red-datos: { driver: bridge }

volumes:
  db_data:
